<?php

namespace ContactBundle\Repository;

/**
 * PhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends \Doctrine\ORM\EntityRepository
{
    public function personPhoneNumbers()
    {
        $em = $this->getEntityManager();
        $phones = $em->createQuery('SELECT p FROM ContactBundle:Phone p');
        return $phones;
    }
}
